### ISSUE TITLE
Append Text to Node

### ISSUE THREAD

**Issue by TheFox** [tinfoilboy/CTML#18]
How can I append a text to a node?

For example:

```c++
CTML::Node par{"p", "Hello world "};
...
par.AppendText("text");
```

Or, how can I create this node?

```html
<p>Hello world. <span>Hello</span> You</p>
```

**Comment by tinfoilboy** [comment]
Initially, that was a dumb design choice on my part. I only allowed for one single content text per element.

With that being said, the commit above adds a text node type where only content is printed. That means that, setting content on an element is effectively deprecated and should be replaced by just instantiating the node and using `AppendText`.

To create the node in your example, you would do the following:
```cpp
CTML::Node par("p", "Hello world. ");
par.AppendChild(CTML::Node("span", "Hello"))
   .AppendText(" You");
```
I did make it so that you can still set content when creating a node, which essentially appends a text node on construction.

I hope that this solves your issue!

**Comment by TheFox** [comment]
Nice! Works perfect. As expected. Thank you very much. 👍
