### ISSUE TITLE
Add support for <img>, <href>, and <link> HTML tags

### ISSUE THREAD

**Issue by danielpatenaude** [tinfoilboy/CTML#23]
I made new node types to support these and updated the Node() constructor and ToString() function to support them. It's not perfect and it's very quick and dirty but it added the missing functionality:

This allows images to be used as:
`CTML::Node(CTML::NodeType::IMG, "", "img\\logo.png");`

```
Node(
	const NodeType& type,
	std::string name="",
	std::string content=""
)
.
.
.
else if (type == NodeType::IMG
	|| type == NodeType::HREF
	|| type == NodeType::LINK)
{
	this->SetName(name);
	m_content = content;
}
```

```
std::string ToString(ToStringOptions options={}) const
.
.
.
else if (m_type == NodeType::IMG)
{
	output << indent << "<img " ;
	output << "src=" << m_content << ">";
}
else if (m_type == NodeType::HREF)
{
	output << indent << "<a href=" << m_content << ">" << m_name << "</a>";
}
else if (m_type == NodeType::LINK)
{
	output << indent << "<link " << m_content << "/>";
}
```

**Comment by danielpatenaude** [comment]
I figured it wouldn't hurt to try and contribute to this repo since the work done here is amazing. Having a C++ header library to perform HTML writing saved me hours making my own. I'm just trying to help extend it before I fork my own copy :).

**Comment by tinfoilboy** [comment]
Hey!

I appreciate the issue but unfortunately I think this is out of the scope of this library. One of my main concerns is that, due to how rapidly the HTML specification can evolve, I don't want to hard code elements in. This functionality also is already in the library, though, unfortunately I did neglect to document the important part for self closing tags.

To make a self-closing tag, all you'd need is the following:

```cpp
CTML::Node` img("img");

img.SetAttribute("src", "https://example.com/image.png");
img.UseClosingTag(false);
```
This would then give an output of `<img src="https://example.com/image.png">`. Though I may add a method to compare known self-closing tags and if one is detected, set the closing tag to not be used automatically.

For an `<a>` element you'd also just have to construct it as such and then set the `href` attribute to whatever link you want the anchor to point to.

Again though, thank you for using the library!
